# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gHDLGwRq_VQCNErwPqaghii8QWrrh3i0
"""

def naive_data_preparation(dataset):

  '''
  
  Function used to fill in the gaps with mean for continous features and mode for the discrete ones and apply
  naive label encoding without concerns about the suitability of dummy variables.

  '''

  from sklearn.preprocessing import LabelEncoder


  for column in dataset.columns:
    if dataset[column].dtype != 'object':
        dataset[column].fillna(dataset[column].mean(), inplace= True)
    else:
        dataset[column] = dataset[column].astype('str')
        dataset[column].fillna(dataset[column].mode(), inplace= True)

  
  le = LabelEncoder()

  for column in dataset.columns:
    if dataset[column].dtype == 'object':
      dataset[column] = le.fit_transform(dataset[column])