# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gHDLGwRq_VQCNErwPqaghii8QWrrh3i0
"""

def squared_ab(a, b):
  return a**b